name: CI - FiapCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.405'

      - name: Restore
        run: dotnet restore FiapCloud.sln

      - name: Build
        run: dotnet build FiapCloud.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test FiapCloud.Tests/FiapCloud.Tests.csproj --no-build --verbosity normal
